export default [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "coverage/**",
      "cobra-dev-keys.js",
      "api/**",
      "bridge/**",
      "scripts/**",
      "tests/**",
      "eslint.config.js",
      "jest.config.js",
    ],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser & DOM
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        crypto: "readonly",
        indexedDB: "readonly",
        IDBKeyRange: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        // DOM Events (used inside chrome.scripting.executeScript)
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        PointerEvent: "readonly",
        InputEvent: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        CSS: "readonly",
        Node: "readonly",
        DataTransfer: "readonly",
        XPathResult: "readonly",
        location: "readonly",
        navigator: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        URLSearchParams: "readonly",
        AbortSignal: "readonly",
        // Browser dialogs
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        // Web APIs
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        SpeechSynthesisUtterance: "readonly",
        Audio: "readonly",
        MediaRecorder: "readonly",
        // Service Worker
        self: "readonly",
        importScripts: "readonly",
        // Chrome Extension APIs
        chrome: "readonly",
        // COBRA globals (modules loaded via importScripts)
        Result: "readonly",
        COBRA_ERRORS: "readonly",
        COBRA_DEFAULTS: "readonly",
        COBRA_TOOLS: "readonly",
        TOOL_RISK_MAP: "readonly",
        CobraPolicy: "readonly",
        CobraSelectorStats: "readonly",
        CobraJobs: "readonly",
        CobraSupervisor: "readonly",
        CobraIndexedDB: "readonly",
        CobraLogger: "readonly",
        CobraErrorBoundary: "readonly",
        CobraOrchestrator: "readonly",
        CryptoUtils: "readonly",
        StealthMode: "readonly",
        RateLimiter: "readonly",
        Cache: "readonly",
        CacheManager: "readonly",
        PersistenceManager: "readonly",
        TeamAuth: "readonly",
        BrowserAgent: "readonly",
        Agent: "readonly",
        HydraClient: "readonly",
        CobraBrain: "readonly",
        TaskRunner: "readonly",
        FileManager: "readonly",
        FileCreator: "readonly",
        Connectors: "readonly",
        Pipeline: "readonly",
        ElevenLabs: "readonly",
        JobManager: "readonly",
        GateEngine: "readonly",
        ConversationEngine: "readonly",
        DecisionEngine: "readonly",
        KnowledgeBase: "readonly",
        KBCloudSync: "readonly",
        cobraKB: "readonly",
        cobraIDB: "readonly",
        seedKB: "readonly",
        seedKBIfEmpty: "readonly",
        executeToolCall: "readonly",
        ToolSafety: "readonly",
        ProviderRouter: "readonly",
        CobraRouter: "readonly",
        validateToolArgs: "readonly",
        execScriptWithTimeout: "readonly",
        dismissCookiePopups: "readonly",
        logAction: "readonly",
        actionLog: "readonly",
        commConfig: "readonly",
        commAutodiscover: "readonly",
        getErrorDef: "readonly",
        // Additional COBRA globals
        Brain: "readonly",
        Library: "readonly",
        Stealth: "readonly",
        COBRAError: "readonly",
        OnboardingWizard: "readonly",
        cobraGate: "readonly",
        cobraKBSync: "readonly",
        cobraOrchestrator: "readonly",
        scrapeTab: "readonly",
        loadFilesList: "readonly",
        loadTasksList: "readonly",
        RELAY: "readonly",
        relayLog: "readonly",
        results: "writable",
        module: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-constant-condition": "warn",
      "no-debugger": "error",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "warn",
      "no-irregular-whitespace": "warn",
      "no-unreachable": "warn",
      "eqeqeq": ["warn", "smart"],
      "no-eval": "warn",
      "no-implied-eval": "warn",
      "no-new-func": "warn",
      "no-throw-literal": "warn",
      "prefer-const": "warn",
      "no-var": "warn",
    },
  },
];
